DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USERS;

/*DROP SEQUENCE IF EXISTS global_seq;
CREATE SEQUENCE GLOBAL_SEQ START WITH 100000;*/

CREATE TABLE USERS
(
    ID         BIGINT                  NOT NULL,
    NAME       VARCHAR(255)            NOT NULL,
    EMAIL      VARCHAR(255)            NOT NULL,
    PASSWORD   VARCHAR(255)            NOT NULL,
    REGISTERED TIMESTAMP DEFAULT NOW() NOT NULL,
    ENABLED    BOOLEAN   DEFAULT TRUE  NOT NULL
);
ALTER TABLE USERS
    ADD CONSTRAINT USERS_ID PRIMARY KEY (ID);
ALTER TABLE USERS
    ADD CONSTRAINT UNIQUE_USERS_EMAIL_IDX UNIQUE (EMAIL);

CREATE TABLE USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE    VARCHAR(255)
);